services:
  consul:
    image: hashicorp/consul:1.21
    container_name: consul # used as service name in hcl files
    ports:
      - "8500:8500"
    command: "agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -data-dir=/consul/data"
    volumes:
      - consul_data:/consul/data

  vault: 
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK  # For Vault to lock memory (prevents sensitive data from being swapped to disk)
    volumes:
      - vault-data:/vault/data
      - vault-logs:/vault/logs
      - ./vault-config/prod:/vault/config
    command: vault server -config=/vault/config/vault.hcl

    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - consul

  vault-ui:
    image: djenriquez/vault-ui:latest
    container_name: vault-ui
    ports:
      - "8000:8000"
    environment:
      VAULT_URL_DEFAULT: http://vault:8200
      VAULT_AUTH_DEFAULT: TOKEN
    depends_on:
      - vault

volumes:
  consul_data:
  vault-data:
  vault-logs:

